apiVersion: v1
kind: Pod
metadata:
  name: postinstall-hook1
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  containers:
  - name: post-install-container
    image: busybox
    imagePullPolicy: Always
    command: ['sh', '-c', 'sleep 10']
  restartPolicy: Never
  terminationGracePeriodSeconds: 0