apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: combined-app-python
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: app.python
      http
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-python-service
                port:
                  number: 5001