password: ENC[AES256_GCM,data:rJ8vFsYpIDbLQt==,iv:y0JfZTpeFU//t0sQj8nGiLbF9o72zJRp5hVxX6o1Pd+I=,tag:z0qYxH0w6eXsD42zOvN8LK==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-16T08:28:34Z"
    mac: ENC[AES256_GCM,data:OZ7BzK5S6vR3f2bGaR0k8jP9iL5rN3dG4V9cJ0kW1zX3c7bH8pR5vD6lO1a2j5bV0rN2sP1cB6t7iN4m8oP3qR7w9kL0j7f4gS5dR2f3s4d6g8dK2a3e4w7g8b9d0e6z9b3e8b7c8/P0rJsV2oCl7zWfDaM1lE6r9kYbQ3tP4qX0dC2wV9kT3gR7hJ8mS5jN2lA6eN9cP8sR1zE0=,iv:P7mKeFjP2rC3sZtR8vD9aG1wL0jN6qX9/gvLMsDws=,tag:T5kMzPwRdVnF2eKlYtGh==,type:str]

    pgp:
        - created_at: "2024-04-16T08:28:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----
            wU6C3pFj0Hq8sV9ZGIpNd/2kiSFOEfbM/19oXVJyCnEaR9xG/Y3E7rH4O+XywQgD
            8VMDhGJLoTaNyY7cH/NkZkg/eVVw3sp4A+8xJHdyP/ZcY9X6P3Uv6cFvQjpyiE2
            3lO6Y/33WhZ9iMgjPxESeufN9YPpLM6mN+g/F/I3SaWLrW/5Gp2vRojJ2eAeWaJ
            X/qL517VkTiK7r6KQSx9sW9E9/W5n3R9UQ+b1RlN65JqO0R1o/JKz5/Q8k9xz2W
            =+UT0
            -----END PGP MESSAGE-----
          fp: AB56B10AFA100A03F671F6F13F05D5AAE541F0C3
    unencrypted_suffix: _unencrypted
    version: 3.8.1