name: app python workflow

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Dependencies
        working_directory: 'app_python'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Testing
        working_directory: 'app_python'
        run: |
          python install flake8
          pip flake8

  linting:
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Linting
        uses: actions/setup-python@v4
        with:
            python-version: "3.9"
      - name: flake8 Lint
        run: |
          python install flake8
          pip flake8

  snyk:
      runs-on: ubuntu-latest
      needs:
        - build_and_test
      steps:
        - uses: actions/checkout@v2

        - name: snyk
          uses: snyk/actions/python-3.11@master
          with:
            args: --skip-unresolved app_python/
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
